services:
  provider:
      image: viniciussf/customer-provider:latest
      container_name: customer-provider
      ports:
        - "8081:8080"
      networks:
        - customer-network

  consumer:
      image: viniciussf/customer-consumer:latest
      container_name: customer-consumer
      ports:
        - "8082:8080"
      depends_on:
        - provider
      networks:
        - customer-network

networks:
  customer-network:
    #driver: bridge
